### ISSUE TITLE
support crystal 0.21.0

### ISSUE THREAD

**Issue by metacortex** [ysbaddaden/crystal-alpine#2]
This link is for 0.19.X.
https://dl.dropboxusercontent.com/u/53345358/alpine/setup.txt

Any newer version available?

**Comment by ysbaddaden** [comment]
Yes, it's now at http://public.portalier.com/alpine but I think v0.21.0 isn't available, yet.

**Comment by metacortex** [comment]
Wow. cool.
Thanks
