### ISSUE TITLE
Put a link to the website on this repo

### ISSUE THREAD

**Issue by kirbyfan64** [ysbaddaden/crystal-alpine#3]
http://public.portalier.com/alpine

This repo is the first Google search result for *crystal alpine linux*. I assumed that it was some sort of specialized thing and ended up passing over it and trying to get Crystal working from the binary releases (which was a total pain in the neck, BTW). An hour later, I stumbled upon your tweet:

https://twitter.com/ysbaddaden/status/839437755742568448

followed by one of the most epic facepalm moments I've ever had. :O

**Comment by ysbaddaden** [comment]
Good idea, thanks!
