### ISSUE TITLE
Doesn't work on alpine 3.6

### ISSUE THREAD

**Issue by RX14** [ysbaddaden/crystal-alpine#4]
It seems that alpine has upgraded to libevent 2.1 as of alpine 3.6. This means that the old shards build no longer works with the error
```
  so:libevent-2.0.so.5 (missing):
    required by:
                 shards-0.7.1-r1[so:libevent-2.0.so.5]
```

The very latest 2 crystal versions do seem to work however.

**Comment by ysbaddaden** [comment]
I updated the crystal APKBUILD but i forgot to recompile Shards.

**Comment by RX14** [comment]
Do you know when you might have the time to do that?

**Comment by ysbaddaden** [comment]
Rebuilt and reuploaded.
