### ISSUE TITLE
[enhancement] Ensure authenticity of artifacts

### ISSUE THREAD

**Issue by josephcopenhaver** [ysbaddaden/crystal-alpine#5]
I was going down the road of building crystal/shard for alpine before I was pointed to this repository by the community on IRC ( thanks a bunch btw guys! )

I really prefer to ensure the authenticity of my dependencies and one easy way to achieve that end is through PGP and SSL.

Could you enable https traffic to public.portalier.com/alpine ? Or could you submit the packages to pkgs.alpinelinux.org 's edge repository for the next alpine release?

**Comment by ysbaddaden** [comment]
Sadly I can't enable https on my host, otherwise I would have.

That being said, alpine packages are signed.

**Comment by josephcopenhaver** [comment]
https://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management#Packages_and_Repositories
Oops, looks like I should read more before opening issues.

Thanks!
