### ISSUE TITLE
Builds for armhf and aarch64

### ISSUE THREAD

**Issue by j8r** [ysbaddaden/crystal-alpine#6]
Thank you for this useful Alpine packages. For now there are `x86` and `x86_64` builds, can the `armhf` and `aarch64` builds be available too?

For now, I'm considering to cross-compile the compiler from "x86_64" to ARM, and then link it in a container running an ARM Alpine through QEMU. If you need I can try to do it and provide you ready to use compilers in order to bootstrap on the ARM architectures.

An other thing: is it possible to remove the `--disable-static` in the APKBUILD of libgc to be able to link statically, as in crystal-lang/crystal/issues/4276?

**Comment by ysbaddaden** [comment]
I'm interested in alpine arm qemu images if you have some. Yet, I'm not sure I'll have dedicated time to build these additional architectures.

We don't need the updated GC anymore, alpine already provides v7.6+

**Comment by j8r** [comment]
I've made a project to do so, [apps-static](https://github.com/DFabric/apps-static). Basically, it uses Docker and special static builds of qemu to run a shell inside ARM images.

If you prefer LXC, I've not found templates, and [no official ones are available yet](
https://jenkins.linuxcontainers.org/view/All%20projects/view/LXC/job/lxc-template-alpine/).

For GC, I will compile one my self to include `.a` archives.

No problem if you have not the time for the builds, I will try to do it on my side. If I succeed, you will be able to package them for Alpine, if you like.

**Comment by j8r** [comment]
Good news @ysbaddaden, an [LXC template for Alpine ARMhf](https://jenkins.linuxcontainers.org/job/lxc-template-alpine/) is now available!

**Comment by ysbaddaden** [comment]
AFAIK it needs an ARM host, right?

**Comment by j8r** [comment]
Not necessarily if you run the shell with a [qemu binary](https://bitbucket.org/dfabric/binaries/downloads/). Thanks to https://github.com/resin-io/qemu, all subcommands executed via the shell will be also runned with qemu. It works with Docker, it should also work with other container runtimes.

**Comment by ysbaddaden** [comment]
Sweet, I created a rootfs with usr/bin/qemu-arm-static, got the latest lxc-alpine template (hacked it to support an older LXC version) and now I have an alpine-armhf container, but I can't setup network inside :sob:

**Comment by j8r** [comment]
We can close the issue, @jirutka has published for x86-64 and aarch64 on the [edge branch of Alpine](https://pkgs.alpinelinux.org/packages?name=crystal&branch=edge) and probably will for armhf when it will be ready.
Thanks to him and you!

**Comment by jirutka** [comment]
FYI, I’ve already moved it from testing to the community repo, so it will be included in the upcoming Alpine v3.8 release.

> …probably will for armhf when it will be ready.

I’d like to, but arm-linux-musleabihf support is currently broken (see #5862). :(
