### ISSUE TITLE
crystal build doesn't work under alpine:3.7 Docker

### ISSUE THREAD

**Issue by aisrael** [ysbaddaden/crystal-alpine#7]
Am trying to use this to build a minimal Crystal runtime Docker container.

Here's what I did
```
$ docker run -v $(pwd):/src --rm -it alpine:3.7 sh
/ # echo http://public.portalier.com/alpine/testing >> /etc/apk/repositories
/ # wget http://public.portalier.com/alpine/julien%40portalier.com-56dab02e.rsa.pub -O /etc/apk/keys/julien@portalier.com-56dab02e.rsa.pub
/ # apk update
/ # apk add crystal shards
/ # cd /src
/src # crystal build --release hello.cr
--: line 1: cc: not found
Error: execution of command failed with code: 127: `cc "${@}" -o '/src/hello'  -rdynamic  -lpcre -lgc -lpthread /usr/lib/crystal/src/ext/libcrystal.a -levent -lrt -L/usr/lib -L/usr/local/lib`
```

Am guessing I need the `cc` package? But am using the APKs you already provided, so, I can't just have `crystal` running on its own?

**Comment by ysbaddaden** [comment]
Yes, you need a C compiler to eventually link programs. I probably overlooked that since I always add `build-base` myself.

You'll may want to use https://hub.docker.com/r/ysbaddaden/crystal-alpine/ for an alpine+crystal docker image. It's always up-to-date, and automatically (re)built.

**Comment by aisrael** [comment]
Thanks. Since this is just research for now I'll use your image. Eventually though, I think I'll need to figure out how to build our own images, even if I end up having to compile `crystal` itself on alpine.

**Comment by aisrael** [comment]
Thanks. Since this is just research for now I'll use your image. Eventually though, I think I'll need to figure out how to build our own images, even if I end up having to compile `crystal` itself on alpine.

**Comment by aisrael** [comment]
So now my problem is that am trying to build a simple API that uses [kemal](https://github.com/kemalcr/kemal) and am getting

```
Package libssl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libssl.pc'
```

Even after I've `apk add openssl`

**Comment by ysbaddaden** [comment]
You need development packages.
